# LambdaTest AI Cloud Configuration
project_id: "your_project_id"
folder_id: "your_folder_id"
assignee: your_user_id
environment_id: environment_id
test_url: "https://stirring-cheesecake-c47db8.netlify.app/"
